# Generated by Django 5.2.5 on 2025-09-09 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('filetype', models.CharField(choices=[('lebenslauf', 'Lebenslauf'), ('rechnung', 'Rechnung'), ('anschreiben', 'Anschreiben')], max_length=20)),
                ('filelocation', models.FileField(upload_to='uploaded_documents/%Y/%m/%d/')),
                ('file_address_key', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('uploadtime', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uploaded File',
                'verbose_name_plural': 'Uploaded Files',
                'ordering': ['-uploadtime'],
            },
        ),
        migrations.CreateModel(
            name='LebenslaufMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('primary_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('primary_email', models.CharField(blank=True, max_length=255, null=True)),
                ('urls', models.TextField(blank=True, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=255, null=True)),
                ('github', models.CharField(blank=True, max_length=255, null=True)),
                ('fulladdress', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('workexperiance', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='lebenslauf_metadatas', to=settings.AUTH_USER_MODEL)),
                ('file_key', models.ForeignKey(db_column='file_key', on_delete=django.db.models.deletion.CASCADE, related_name='metadatas', to='home_app.uploadedfile')),
            ],
            options={
                'db_table': 'lebenslauf_metadata',
            },
        ),
        migrations.AddIndex(
            model_name='uploadedfile',
            index=models.Index(fields=['user'], name='home_app_up_user_id_ef9f20_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedfile',
            index=models.Index(fields=['-uploadtime'], name='home_app_up_uploadt_ef2baf_idx'),
        ),
        migrations.AddConstraint(
            model_name='lebenslaufmetadata',
            constraint=models.UniqueConstraint(fields=('file_key',), name='uq_lebenslauf_metadata_file_key'),
        ),
    ]
